"""initial

Revision ID: 1402eb24e0ec
Revises: 
Create Date: 2021-04-30 18:10:07.898084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1402eb24e0ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('type', sa.Enum('tech', 'biz', name='skill_types'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('useraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('Seeker', 'Company', 'Admin', name='account_types'), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password', sa.String(length=191), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companyprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=191), server_default=sa.text('NULL'), nullable=True),
    sa.Column('city', sa.String(length=191), server_default=sa.text('NULL'), nullable=True),
    sa.Column('state', sa.String(length=2), server_default=sa.text('NULL'), nullable=True),
    sa.Column('website', sa.String(length=191), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('seekerprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=191), nullable=False),
    sa.Column('last_name', sa.String(length=191), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=191), server_default=sa.text('NULL'), nullable=True),
    sa.Column('state', sa.String(length=2), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seeker_id')
    )
    op.create_table('jobpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=191), nullable=False),
    sa.Column('description', sa.String(length=191), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companyprofile.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobpost')
    op.drop_table('seekerprofile')
    op.drop_table('companyprofile')
    op.drop_table('useraccount')
    op.drop_table('skill')
    op.drop_table('attitude')
    # ### end Alembic commands ###
