"""empty message

Revision ID: 272d2d7beb20
Revises: 1402eb24e0ec
Create Date: 2021-05-22 22:25:42.202502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272d2d7beb20'
down_revision = '1402eb24e0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SeekerHistoryEducation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('education_lvl', sa.String(), nullable=False),
    sa.Column('study_field', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_abv', sa.String(), nullable=True),
    sa.Column('active_enrollment', sa.SMALLINT(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SeekerHistoryJob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=191), server_default=sa.text('NULL'), nullable=True),
    sa.Column('state', sa.String(length=2), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SeekerSkill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('1', '2', '3', '4', '5', name='skill_levels'), nullable=False),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companypicture',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['companyprofile.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'user_id')
    )
    op.create_table('seekerAttitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('attitude_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attitude_id'], ['attitude.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekerprofile.seeker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seekerpicture',
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('original', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['seekerprofile.id'], ),
    sa.PrimaryKeyConstraint('width', 'height', 'user_id')
    )
    op.create_table('Applied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SeekerSearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('Want to apply', 'Considering to apply', 'Will not apply', name='job_labels'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobpostattitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobpost_id', sa.Integer(), nullable=False),
    sa.Column('attitude_id', sa.Integer(), nullable=False),
    sa.Column('importance_level', sa.Enum('1', '2', '3', '4', '5', '6', '7', name='important_level'), nullable=False),
    sa.ForeignKeyConstraint(['attitude_id'], ['attitude.id'], ),
    sa.ForeignKeyConstraint(['jobpost_id'], ['jobpost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobpostskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobpost_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level_min', sa.Enum('1', '2', '3', '4', '5', name='skill_levels'), nullable=False),
    sa.Column('importance_level', sa.Enum('1', '2', '3', '4', '5', '6', '7', name='important_level'), nullable=False),
    sa.ForeignKeyConstraint(['jobpost_id'], ['jobpost.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobpost', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('jobpost', sa.Column('city', sa.String(length=191), nullable=True))
    op.add_column('jobpost', sa.Column('is_remote', sa.Boolean(), nullable=True))
    op.add_column('jobpost', sa.Column('state_abbv', sa.String(length=2), nullable=True))
    op.add_column('seekerprofile', sa.Column('resume', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seekerprofile', 'resume')
    op.drop_column('jobpost', 'state_abbv')
    op.drop_column('jobpost', 'is_remote')
    op.drop_column('jobpost', 'city')
    op.drop_column('jobpost', 'active')
    op.drop_table('jobpostskill')
    op.drop_table('jobpostattitude')
    op.drop_table('SeekerSearch')
    op.drop_table('Bookmarks')
    op.drop_table('Applied')
    op.drop_table('seekerpicture')
    op.drop_table('seekerAttitude')
    op.drop_table('companypicture')
    op.drop_table('SeekerSkill')
    op.drop_table('SeekerHistoryJob')
    op.drop_table('SeekerHistoryEducation')
    # ### end Alembic commands ###
