"""add applictn/bookmark

Revision ID: 28f8aacd9931
Revises: 8f48ad319ee9
Create Date: 2021-05-24 14:44:36.282076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f8aacd9931'
down_revision = '8f48ad319ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeker_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobpost.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seeker_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobpost.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeker_bookmark')
    op.drop_table('seeker_application')
    # ### end Alembic commands ###
