"""add seeker attributes

Revision ID: a373c306be3a
Revises: 955c3aaae008
Create Date: 2021-05-24 14:18:21.584166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a373c306be3a'
down_revision = '955c3aaae008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeker_attitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('attitude_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attitude_id'], ['attitude.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seeker_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', postgresql.ENUM('novice', 'familiar', 'competent', 'proficient', 'expert', name='skilllevels'), nullable=False),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeker_skill')
    op.drop_table('seeker_attitude')
    # ### end Alembic commands ###
