"""add job post

Revision ID: e77705401a3f
Revises: a373c306be3a
Create Date: 2021-05-24 14:21:10.719846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77705401a3f'
down_revision = 'a373c306be3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=191), nullable=False),
    sa.Column('city', sa.String(length=191), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobpost')
    # ### end Alembic commands ###
